#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

//! # Rust Abieos
//!
//! Abieos is a Rust wrapper for the abieos C library

use std::ffi::{CStr, CString};
use std::os::raw::c_char;

mod abieos_error;

pub use abieos_error::AbieosError;

pub mod bindings {
    // Generated by build.rs into OUT_DIR (never the source tree). On docs.rs
    // build.rs copies the committed src/bindings.rs here instead.
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;

fn string_from_ptr(ptr: *const c_char) -> String {
    unsafe {
        CStr::from_ptr(ptr).to_str().expect("Failed to convert CStr to str").to_string()
    }
}

/// Abieos is a Rust wrapper for the abieos C library.
///
/// # Thread Safety
///
/// `Abieos` implements `Send` but **not** `Sync`. The underlying C library stores
/// mutable state (result buffers, error strings) in the context struct, so concurrent
/// access from multiple threads is **not safe**.
///
/// Instead of wrapping in `Arc<Mutex<Abieos>>`, create one `Abieos` per thread/task:
/// ```rust,no_run
/// use rs_abieos::Abieos;
/// // Each thread gets its own context — no contention
/// let abieos = Abieos::new();
/// ```
pub struct Abieos {
    context: *mut abieos_context,
    owns_context: bool,
}

unsafe impl Send for Abieos {}

/// Accepted name formats
pub enum NameLike {
    String(String),
    StringRef(&'static str),
    U64(u64),
    I32(i32),
}

/// Accepted ABI formats
pub enum AbiLike {
    Json(String),
    Hex(String),
    Bin(Vec<u8>),
}

/// Abieos Contract reference
pub struct AbieosContract {
    pub context: *mut abieos_context,
    pub name: u64,
    pub abiLoaded: bool,
}

impl AbieosContract {
    //! # Abieos Contract
    //!
    //!  AbieosContract is a contract reference that can be used to load ABIs and serialize/deserialize data
    //!

    /// Load an ABI from a JSON file
    pub fn load_json_file(&mut self, path: &str) -> Result<&mut Self, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        match std::fs::read_to_string(path) {
            Ok(file) => {
                match ref_abieos.set_abi_json_native(self.name, &file) {
                    Ok(_) => {
                        self.abiLoaded = true;
                        Ok(self)
                    }
                    Err(e) => Err(e)
                }
            }
            Err(_) => Err(AbieosError::FileRead),
        }
    }

    /// Load an ABI
    pub fn load_abi(&mut self, abi: AbiLike) -> Result<&mut Self, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        let result = match abi {
            AbiLike::Json(abi_json) => {
                ref_abieos.set_abi_json_native(self.name, &abi_json)
            }
            AbiLike::Hex(abi_hex) => {
                ref_abieos.set_abi_hex_native(self.name, &abi_hex)
            }
            AbiLike::Bin(abi_bin) => {
                ref_abieos.set_abi_bin_native(self.name, &abi_bin)
            }
        };
        match result {
            Ok(_) => {
                self.abiLoaded = true;
                Ok(self)
            }
            Err(e) => Err(e)
        }
    }

    /// Get data type for an action
    pub fn get_type_for_action(&self, action: &str) -> Result<String, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        match ref_abieos.string_to_name(action) {
            Ok(x) => ref_abieos.get_type_for_action_native(self.name, x),
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Get data type for a table
    pub fn get_type_for_table(&self, table: &str) -> Result<String, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        match ref_abieos.string_to_name(table) {
            Ok(x) => ref_abieos.get_type_for_table_native(self.name, x),
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Serialize JSON into binary (output as HEX)
    pub fn json_to_hex(&self, datatype: &str, json: &str) -> Result<String, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        ref_abieos.json_to_hex_native(self.name, datatype, json)
    }

    /// Deserialize HEX string into JSON
    pub fn hex_to_json(&self, datatype: &str, hex: &str) -> Result<String, AbieosError> {
        let ref_abieos = Abieos::from_context(self.context);
        ref_abieos.hex_to_json_native(self.name, datatype, hex)
    }
}

impl AbieosContract {
    pub fn new(context: *mut abieos_context, name: u64) -> AbieosContract {
        AbieosContract { context, name, abiLoaded: false }
    }
}

impl Abieos {
    /// Reference a contract by name
    pub fn contract(&self, account_name: NameLike) -> AbieosContract {
        match account_name {
            NameLike::StringRef(name) => {
                let name_u64 = self.string_to_name(name)
                    .expect("Failed to convert name to u64");
                AbieosContract::new(self.ctx(), name_u64)
            }
            NameLike::String(name) => {
                let name_u64 = self.string_to_name(name.as_str())
                    .expect("Failed to convert name to u64");
                AbieosContract::new(self.ctx(), name_u64)
            }
            NameLike::U64(name) => {
                AbieosContract::new(self.ctx(), name)
            }
            NameLike::I32(name) => {
                AbieosContract::new(self.ctx(), name as u64)
            }
        }
    }
}

impl Default for Abieos {
    fn default() -> Self {
        Abieos::new()
    }
}

impl Drop for Abieos {
    fn drop(&mut self) {
        if self.owns_context && !self.context.is_null() {
            unsafe { abieos_destroy(self.context); }
        }
    }
}

impl Abieos {
    /// Create a new Abieos instance.
    ///
    /// The context is owned and will be automatically freed when dropped.
    pub fn new() -> Abieos {
        Abieos {
            context: abieos::create(),
            owns_context: true,
        }
    }

    /// Create a non-owning Abieos wrapper from an existing context pointer.
    ///
    /// The caller retains ownership of the context — it will **not** be freed
    /// when this wrapper is dropped. This is useful for creating temporary
    /// references to a context managed elsewhere.
    pub fn from_context(context: *mut abieos_context) -> Abieos {
        Abieos {
            context,
            owns_context: false,
        }
    }

    /// Returns the raw context pointer.
    ///
    /// Useful for interop with code that needs direct FFI access.
    pub fn as_ptr(&self) -> *mut abieos_context {
        self.context
    }

    /// Get the last error message
    fn get_error(&self) -> String {
        let ctx = self.ctx();
        unsafe {
            let error = abieos_get_error(ctx);
            CStr::from_ptr(error).to_str().unwrap().to_string()
        }
    }

    /// Get the context pointer
    fn ctx(&self) -> *mut abieos_context {
        self.context
    }

    /// Convert a string slice into an u64 native name
    pub fn string_to_name(&self, name: &str) -> Result<u64, AbieosError> {
        let ctx = self.ctx();
        if name.len() > 13 {
            return Err(AbieosError::NameTooLong);
        }
        unsafe {
            let c_buf = CString::new(name.as_bytes()).unwrap();
            Ok(abieos_string_to_name(ctx, c_buf.as_ptr()))
        }
    }

    /// Convert a C-string into an u64 native name
    pub fn c_string_to_name(&self, name: &CStr) -> u64 {
        let ctx = self.ctx();
        if name.to_bytes().len() > 13 {
            return 0;
        }
        unsafe {
            abieos_string_to_name(ctx, name.as_ptr())
        }
    }

    /// Convert a u64 native name into an owned `String`.
    ///
    /// Returns an owned value: the underlying C call writes into a buffer that
    /// the context reuses on the next call, so a borrowed return would dangle
    /// across subsequent calls (a use-after-free reachable from safe code).
    pub fn name_to_string(&self, name: u64) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        unsafe {
            let c_buf = abieos_name_to_string(ctx, name);
            if c_buf.is_null() {
                // abieos_name_to_string is wrapped in handle_exceptions, which
                // returns null on a null context or a C++ exception
                // (e.g. bad_alloc). CStr::from_ptr(null) is UB, so guard it.
                return Err(AbieosError::NameToString);
            }
            match CStr::from_ptr(c_buf).to_str() {
                Ok(x) => Ok(x.to_string()),
                Err(_) => Err(AbieosError::NameToString),
            }
        }
    }

    /// Convert a u64 native name into an owned `CString`.
    ///
    /// Owned for the same reason as [`name_to_string`](Self::name_to_string).
    /// Returns `Err` if the FFI call yields a null pointer — the C wrapper
    /// returns null on a null context or a C++ exception (e.g. `bad_alloc`).
    pub fn name_to_cstr(&self, name: u64) -> Result<CString, AbieosError> {
        let ctx = self.ctx();
        unsafe {
            let c_buf = abieos_name_to_string(ctx, name);
            if c_buf.is_null() {
                return Err(AbieosError::NameToString);
            }
            Ok(CStr::from_ptr(c_buf).to_owned())
        }
    }

    /// Load a contract ABI to memory (JSON format)
    pub fn set_abi_json(&self, contract: &str, abi_json: &str) -> Result<bool, AbieosError> {
        match self.string_to_name(contract) {
            Ok(contract_u64) => unsafe {
                let abi_content_cs = CString::new(abi_json).unwrap();
                match abieos_set_abi(self.ctx(), contract_u64, abi_content_cs.as_ptr()) {
                    1 => Ok(true),
                    _ => Err(AbieosError::SetAbi(self.get_error()))
                }
            }
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Load a contract ABI to memory (JSON format as C-String)
    pub fn set_abi_json_c(&self, contract: &str, abi_json: &CStr) -> Result<bool, AbieosError> {
        match self.string_to_name(contract) {
            Ok(contract_u64) => unsafe {
                match abieos_set_abi(self.ctx(), contract_u64, abi_json.as_ptr()) {
                    1 => Ok(true),
                    _ => Err(AbieosError::SetAbi(self.get_error()))
                }
            }
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Load a contract ABI to memory (JSON format)
    pub fn set_abi_json_native(&self, contract_u64: u64, abi_json: &str) -> Result<bool, AbieosError> {
        let abi_content_cs = CString::new(abi_json).unwrap();
        unsafe {
            match abieos_set_abi(self.ctx(), contract_u64, abi_content_cs.as_ptr()) {
                1 => Ok(true),
                _ => Err(AbieosError::SetAbi(self.get_error()))
            }
        }
    }

    /// Load a contract ABI to memory (HEX format)
    pub fn set_abi_hex(&self, contract: &str, abi_hex: &str) -> Result<bool, AbieosError> {
        let abi_hex_cs = CString::new(abi_hex).unwrap();
        match self.string_to_name(contract) {
            Ok(contract_u64) => unsafe {
                match abieos_set_abi_hex(self.ctx(), contract_u64, abi_hex_cs.as_ptr()) {
                    1 => Ok(true),
                    _ => Err(AbieosError::SetAbi(self.get_error()))
                }
            }
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Load a contract ABI to memory (HEX format, u64 contract name)
    pub fn set_abi_hex_native(&self, contract: u64, abi_hex: &str) -> Result<bool, AbieosError> {
        let abi_hex_cs = CString::new(abi_hex).unwrap();
        unsafe {
            match abieos_set_abi_hex(self.ctx(), contract, abi_hex_cs.as_ptr()) {
                1 => Ok(true),
                _ => Err(AbieosError::SetAbi(self.get_error()))
            }
        }
    }

    /// Load a contract ABI to memory (binary format)
    pub fn set_abi_bin(&self, contract: &str, abi_bin: &[u8]) -> Result<bool, AbieosError> {
        match self.string_to_name(contract) {
            Ok(contract_u64) => unsafe {
                let abi_bin_data: *const c_char = abi_bin.as_ptr() as *const c_char;
                let abi_bin_size: usize = abi_bin.len();
                match abieos_set_abi_bin(self.ctx(), contract_u64, abi_bin_data, abi_bin_size) {
                    1 => Ok(true),
                    _ => Err(AbieosError::SetAbi(self.get_error()))
                }
            }
            Err(_) => Err(AbieosError::StringToName)
        }
    }

    /// Load a contract ABI to memory (binary format, u64 contract name)
    pub fn set_abi_bin_native(&self, contract: u64, abi_bin: &[u8]) -> Result<bool, AbieosError> {
        let abi_bin_data: *const c_char = abi_bin.as_ptr() as *const c_char;
        let abi_bin_size: usize = abi_bin.len();
        unsafe {
            match abieos_set_abi_bin(self.ctx(), contract, abi_bin_data, abi_bin_size) {
                1 => Ok(true),
                _ => Err(AbieosError::SetAbi(self.get_error()))
            }
        }
    }

    /// Serialize JSON into binary (output as HEX)
    pub fn json_to_hex(&self, account: &str, datatype: &str, json: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let account = self.string_to_name(account)?;

        let datatype = CString::new(datatype).unwrap();
        let json = CString::new(json).unwrap();
        unsafe {
            match abieos_json_to_bin_reorderable(ctx, account, datatype.as_ptr(), json.as_ptr()) {
                1 => {
                    let p = abieos_get_bin_hex(ctx);
                    Ok(string_from_ptr(p))
                }
                _ => Err(AbieosError::JsonToHex(self.get_error()))
            }
        }
    }

    /// Serialize JSON into binary (output as HEX), C-string in/out.
    ///
    /// Returns an owned `CString`. The result no longer aliases the shared
    /// context buffer, so it stays valid across later calls (the previous
    /// `&CStr` return was clobbered by the next call into the context).
    pub fn json_to_hex_c(
        &self,
        account: &CStr,
        datatype: &CStr,
        json: &CStr,
    ) -> Result<CString, AbieosError> {
        let ctx = self.ctx();
        let account = self.c_string_to_name(account);
        unsafe {
            match abieos_json_to_bin_reorderable(ctx, account, datatype.as_ptr(), json.as_ptr()) {
                1 => {
                    // abieos_get_bin_hex is also wrapped in handle_exceptions
                    // and can return null on a C++ exception.
                    let p = abieos_get_bin_hex(ctx);
                    if p.is_null() {
                        return Err(AbieosError::JsonToHex(self.get_error()));
                    }
                    Ok(CStr::from_ptr(p).to_owned())
                }
                _ => Err(AbieosError::JsonToHex(self.get_error())),
            }
        }
    }

    /// Serialize JSON into binary (output as HEX, u64 account name)
    pub fn json_to_hex_native(&self, account: u64, datatype: &str, json: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let datatype = CString::new(datatype).unwrap();
        let json = CString::new(json).unwrap();
        unsafe {
            match abieos_json_to_bin_reorderable(ctx, account, datatype.as_ptr(), json.as_ptr()) {
                1 => {
                    let p = abieos_get_bin_hex(ctx);
                    Ok(string_from_ptr(p))
                }
                _ => Err(AbieosError::JsonToHex(self.get_error()))
            }
        }
    }

    /// Serialize JSON into binary (output as binary)
    pub fn json_to_bin(&self, account: &str, datatype: &str, json: &str) -> Result<Vec<u8>, AbieosError> {
        let ctx = self.ctx();
        let account = self.string_to_name(account)?;
        let datatype = CString::new(datatype).unwrap();
        let json = CString::new(json).unwrap();
        unsafe {
            match abieos_json_to_bin_reorderable(ctx, account, datatype.as_ptr(), json.as_ptr()) {
                1 => {
                    let p = abieos_get_bin_data(ctx);
                    let len = abieos_get_bin_size(ctx);
                    let mut result: Vec<c_char> = Vec::with_capacity(len as usize);
                    std::ptr::copy_nonoverlapping(p, result.as_mut_ptr(), len as usize);
                    result.set_len(len as usize);
                    Ok(result.iter().map(|&c| c as u8).collect())
                }
                _ => Err(AbieosError::JsonToBin(self.get_error()))
            }
        }
    }

    /// Deserialize HEX string into JSON
    pub fn hex_to_json(&self, account: &str, datatype: &str, hex: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let account = self.string_to_name(account)?;

        let datatype = CString::new(datatype).unwrap();
        let hex = CString::new(hex).unwrap();
        unsafe {
            let p = abieos_hex_to_json(ctx, account, datatype.as_ptr(), hex.as_ptr());
            if p.is_null() {
                Err(AbieosError::HexToJson(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }


    /// Deserialize a HEX string into JSON, C-string in/out.
    ///
    /// Returns an owned `CString`. As well as removing the shared-buffer
    /// aliasing, this fixes a soundness bug: the previous implementation called
    /// `CStr::from_ptr` on the result without a null check, but
    /// `abieos_hex_to_json` returns null on error (undefined behavior).
    pub fn hex_to_json_c(
        &self,
        account: &CStr,
        datatype: &CStr,
        hex: &CStr,
    ) -> Result<CString, AbieosError> {
        let ctx = self.ctx();
        let account = self.c_string_to_name(account);
        unsafe {
            let p = abieos_hex_to_json(ctx, account, datatype.as_ptr(), hex.as_ptr());
            if p.is_null() {
                Err(AbieosError::HexToJson(self.get_error()))
            } else {
                Ok(CStr::from_ptr(p).to_owned())
            }
        }
    }

    /// Deserialize Binary into JSON
    pub fn bin_to_json(&self, account: &str, datatype: &str, bin: &[u8]) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let account = self.string_to_name(account)?;
        let datatype = CString::new(datatype).unwrap();
        let bin_data: *const c_char = bin.as_ptr() as *const c_char;
        let bin_size: usize = bin.len();
        unsafe {
            let p = abieos_bin_to_json(ctx, account, datatype.as_ptr(), bin_data, bin_size);
            if p.is_null() {
                Err(AbieosError::BinToJson(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }

    /// Deserialize HEX string into JSON (u64 account name)
    pub fn hex_to_json_native(&self, account: u64, datatype: &str, hex: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let datatype = CString::new(datatype).unwrap();
        let hex = CString::new(hex).unwrap();
        unsafe {
            let p = abieos_hex_to_json(ctx, account, datatype.as_ptr(), hex.as_ptr());
            if p.is_null() {
                Err(AbieosError::HexToJson(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }


    /// Get the type for an action (string names as input)
    pub fn get_type_for_action(&self, contract: &str, action: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let contract = self.string_to_name(contract)?;
        let action = self.string_to_name(action)?;
        unsafe {
            let p = abieos_get_type_for_action(ctx, contract, action);
            if p.is_null() {
                Err(AbieosError::GetTypeForAction(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }

    /// Get the type for an action (u64 names as input)
    pub fn get_type_for_action_native(&self, contract: u64, action: u64) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let p = unsafe { abieos_get_type_for_action(ctx, contract, action) };
        if p.is_null() {
            Err(AbieosError::GetTypeForAction(self.get_error()))
        } else {
            Ok(string_from_ptr(p))
        }
    }

    /// Get the type for a table
    pub fn get_type_for_table(&self, contract: &str, table: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let contract = self.string_to_name(contract)?;
        let table = self.string_to_name(table)?;
        unsafe {
            let p = abieos_get_type_for_table(ctx, contract, table);
            if p.is_null() {
                Err(AbieosError::GetTypeForTable(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }

    /// Get the type for a table (u64 names as input)
    pub fn get_type_for_table_native(&self, contract: u64, table: u64) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let p = unsafe { abieos_get_type_for_table(ctx, contract, table) };
        if p.is_null() {
            Err(AbieosError::GetTypeForTable(self.get_error()))
        } else {
            Ok(string_from_ptr(p))
        }
    }

    /// Get the type for an action result
    pub fn get_type_for_action_result(&self, contract: &str, action: &str) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let contract = self.string_to_name(contract)?;
        let action_res = self.string_to_name(action)?;
        unsafe {
            let p = abieos_get_type_for_action_result(ctx, contract, action_res);
            if p.is_null() {
                Err(AbieosError::GetTypeForActionResult(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }

    /// Convert ABI binary to JSON
    pub fn abi_bin_to_json(&self, abi: &[u8]) -> Result<String, AbieosError> {
        let ctx = self.ctx();
        let abi_bin_data: *const c_char = abi.as_ptr() as *const c_char;
        let abi_bin_size: usize = abi.len();
        unsafe {
            let p = abieos_abi_bin_to_json(
                ctx,
                abi_bin_data,
                abi_bin_size,
            );
            if p.is_null() {
                Err(AbieosError::AbiBinToJson(self.get_error()))
            } else {
                Ok(string_from_ptr(p))
            }
        }
    }

    /// Convert ABI JSON to binary
    pub fn abi_json_to_bin(&self, json: &str) -> Result<Vec<u8>, AbieosError> {
        let ctx = self.ctx();
        let abi_json: CString = CString::new(json).unwrap();
        unsafe {
            match abieos_abi_json_to_bin(ctx, abi_json.as_ptr()) {
                1 => {
                    let p = abieos_get_bin_data(ctx);
                    let len = abieos_get_bin_size(ctx);
                    let mut result: Vec<c_char> = Vec::with_capacity(len as usize);
                    std::ptr::copy_nonoverlapping(p, result.as_mut_ptr(), len as usize);
                    result.set_len(len as usize);
                    Ok(result.iter().map(|&c| c as u8).collect())
                }
                _ => Err(AbieosError::AbiJsonToBin(self.get_error()))
            }
        }
    }

    /// Delete a contract from the context (string name)
    pub fn delete_contract(&self, contract: &str) -> Result<bool, AbieosError> {
        let contract_u64 = self.string_to_name(contract)?;
        self.delete_contract_native(contract_u64)
    }

    /// Delete a contract from the context (u64 name)
    pub fn delete_contract_native(&self, contract: u64) -> Result<bool, AbieosError> {
        let ctx = self.ctx();
        unsafe {
            match abieos_delete_contract(ctx, contract) {
                1 => Ok(true),
                _ => Ok(false),
            }
        }
    }
}

pub mod abieos {
    //! # Abieos
    //!
    //!  Abieos is a Rust wrapper for the abieos C library

    use crate::{abieos_context, abieos_create};

    pub fn create() -> *mut abieos_context {
        unsafe {
            abieos_create()
        }
    }
}
